newtdm

diff --git a/yenv b/yenv
--- a/yenv
+++ b/yenv
@@ -1,45 +1,51 @@
-[ -z "$YBASE" ] && { echo "YBASE not set. Aborting."; return 1; }
-[ -d "$YBASE" ] || { echo "YBASE path invalid. Aborting."; return 1; }
-[ -d "$YBASE/scripts" ] || { echo "scripts path invalid. Aborting."; return 1; }
+[ -z "$YDIR" ] && { echo "YDIR not set. Aborting."; return 1; }
+[ -d "$YDIR" ] || { echo "YDIR path invalid. Aborting."; return 1; }
+[ -d "$YDIR/scripts" ] || { echo "scripts path invalid. Aborting."; return 1; }
 
-alias ymake='make -f $YBASE/scripts/makefile'
+# alias ymake='make -f $YDIR/scripts/makefile'
 
-YDL="$YBASE/downloads"
-YDEPS="$YBASE/deps"
+YDL="$YDIR/downloads"
+YSTAGE="$YDIR/stage"
+YSW="$YDIR/sw"
 
 [ -d "$YDL" ] || mkdir -p $YDL
-[ -d "$YDEPS" ] || mkdir -p $YDEPS
-[ -d "$YBASE/gcc" ] || mkdir -p $YBASE/gcc
-[ -d "$YBASE/codeblocks" ] || mkdir -p $YBASE/codeblocks
+[ -d "$YSTAGE" ] || mkdir -p $YSTAGE
+[ -d "$YSW" ] || mkdir -p $YSW
 
-############# eXtract dependencies in YDL folder to YDEPS folder #############
-xdeps () 
+case "$YOS" in mingw*)
+  [ -d "$YDIR/gcc" ] || mkdir -p $YDIR/gcc
+  [ -d "$YDIR/codeblocks" ] || mkdir -p $YDIR/codeblocks
+esac
+
+
+############# eXtract files in YDL folder to YSTAGE folder #############
+xdeps ()
 {
-  if [ $# -eq 0 ]; then 
+  if [ $# -eq 0 ]; then
     echo -e "\nxdeps needs source filename argument.\n"
     ls -1 $YDL | sort
-	echo -e "\npick one from list printed. "
-	return 1
+    echo -e "\npick one from list shown. "
+    return 1
   fi
 
   [ -z "$YDL" ] && { echo "YDL not set. Aborting."; return 1; }
   [ -d "$YDL" ] || { echo "YDL not set correctly. Aborting."; return 1; }
-  [ -z "$YDEPS" ] && { echo "YDEPS not set. Aborting."; return 1; }
-  [ -d "$YDEPS" ] || { echo "YDEPS not set correctly. Aborting."; return 1; }
-  [ -f "$YDL/$1" ] || { echo "File $YDEPS/$1 not Found. Aborting."; return 1; }
+  [ -z "$YSTAGE" ] && { echo "YSTAGE not set. Aborting."; return 1; }
+  [ -d "$YSTAGE" ] || { echo "YSTAGE not set correctly. Aborting."; return 1; }
+  [ -f "$YDL/$1" ] || { echo "File $YDL/$1 not Found. Aborting."; return 1; }
 
   case "$1" in
-    *.tar.gz) 7za e -aoa $YDL/$1 -so | 7za x -aoa -si -ttar -o$YDEPS ;;
-	*.tar.bz2) 7za e -aoa $YDL/$1 -so | 7za x -aoa -si -ttar -o$YDEPS ;;
-    *.7z) 7za x -aoa $YDL/$1 -o$YDEPS ;;
+    *.tar.gz) tar -zxvf $YDL/$1 -C $YSTAGE ;;
+    *.tar.bz2) tar -jxvf $YDL/$1 -C $YSTAGE ;;
+    *.7z) 7za x -aoa $YDL/$1 -o$YSTAGE ;;
     *) echo "File Format Unsupported $1" ;;
   esac
 }
 
-############# set Y vars using directories in YDEPS folder #############
+############# set Y vars using directories in YSTAGE folder #############
 sdeps()
 {
-for file in `find $YDEPS/* -prune -type d`
+for file in `find $YSW/* -prune -type d`
 do
   filename=$(basename $file)
 
@@ -51,80 +57,72 @@ do
   fi
 
   case $filename in
-    boost*) YBOO=$file
-			echo "YBOO=$YBOO"
-			export YBOO
-			[ -d "$YBOO/stage/lib" ] && YBOOSUFFIX=`find $YBOO/stage/lib -name "libboost_filesystem*.a" | head -1 | awk -Ffilesystem '{print $(NF)}' | cut -d'.' -f1`
-			echo "YBOOSUFFIX=$YBOOSUFFIX"
-			export YBOOSUFFIX ;;
+    boost*) YBOO=$file; echo "YBOO=$YBOO"; export YBOO ;;
     openssl*) YOSSL=$file; echo "YOSSL=$YOSSL"; export YOSSL ;;
     db*) YBDB=$file; echo "YBDB=$YBDB"; export YBDB ;;
-	leveldb*) YLDB=$file; echo "YLDB=$YLDB"; export YLDB ;;
+    leveldb*) YLDB=$file; echo "YLDB=$YLDB"; export YLDB ;;
     miniupnp*) YUPNP=$file; echo "YUPNP=$YUPNP"; export YUPNP ;;
     zlib*) YZLIB=$file; echo "YZLIB=$YZLIB"; export YZLIB ;;
+    libevent*) YEVT=$file; echo "YEVT=$YEVT"; export YEVT ;;
     libpng*) YPNG=$file; echo "YPNG=$YPNG"; export YPNG ;;
     qrenc*) YQR=$file; echo "YQR=$YQR"; export YQR ;;
     qt*) YQT=$file; echo "YQT=$YQT"; export YQT ;;
-	pcre*) YPCRE=$file; echo "YPCRE=$YPCRE"; export YPCRE ;;
-	jansson*) YJANS=$file; echo "YJANS=$YJANS"; export YJANS ;;
-	curl*) YCURL=$file; echo "YCURL=$YCURL"; export YCURL ;;
-	wxWidgets*) YWX=$file; echo "YWX=$YWX"; export YWX ;;
+    pcre*) YPCRE=$file; echo "YPCRE=$YPCRE"; export YPCRE ;;
+    jansson*) YJANS=$file; echo "YJANS=$YJANS"; export YJANS ;;
+    curl*) YCURL=$file; echo "YCURL=$YCURL"; export YCURL ;;
+    wxWidgets*) YWX=$file; echo "YWX=$YWX"; export YWX ;;
   esac
 done
 
 }
 
 ############# unset Y env vars #############
-udeps() 
-{ 
-unset YBOO; unset YBOOSUFFIX; unset YOSSL;unset YBDB;unset YUPNP;unset YZLIB;unset YPNG;unset YQR;unset YQT;unset YWX;unset YPCRE;unset YJANS;unset YCURL;unset YLDB;
-echo -e "\nvariables unset:\nYBOO YOSSL YBDB YUPNP YZLIB YPNG YQR YQT YWX YPCRE YJANS YCURL YLDB"
+udeps()
+{
+unset YBOO; unset YOSSL;unset YBDB;unset YUPNP;unset YZLIB;unset YPNG;unset YQR;unset YQT;unset YWX;unset YPCRE;unset YJANS;unset YCURL;unset YLDB;unset YEVT;
+echo -e "\nvariables unset:\nYBOO YOSSL YBDB YUPNP YZLIB YPNG YQR YQT YWX YPCRE YJANS YCURL YLDB YEVT"
 }
 
-############# find dependency starting with $1 in YDEPS folder #############
+############# find dependency starting with $1 in YSTAGE folder #############
 fdeps()
-{ 
-find $YDEPS/* -prune -type d -name "$1*" | sort; 
+{
+find $YSTAGE/* -prune -type d -name "$1*" | sort;
 }
 
 ############# print current dependancies #############
 pdeps()
 {
-env | grep "^Y" | egrep -v "^YDL|^YDEPS|^YBASE" | sort
-}
-
-############# Boost Library Suffix #############
-yboostsuffix () 
-{
-find $YBOO/stage/lib -name "libboost_filesystem*.a" | head -1 | awk -Ffilesystem '{print $(NF)}' | cut -d'.' -f1
+env | grep "^Y" | egrep -v "^YDL|^YSTAGE|^YDIR" | sort
 }
 
 ############# Print info from environment #############
-yinfo () 
+yinfo ()
 {
 echo -e ""
 set | grep "^build"
 echo -e ""
 set | grep "^Y"
 echo -e ""
-cat $YBASE/scripts/makefile | grep "^[A-z]" | grep -v "SELF_DIR" | awk '{print "ymake "$1}' | sed "s/://g"
+cat $YDIR/scripts/makefile | grep -e "^[[:alpha:]]" | grep -v "SELF_DIR" | awk '{print "ymake "$1}' | sed "s/://g"
 }
 
 ##############################################################################
-if [ -f "$YBASE/scripts/ydeps" ]; then
-source $YBASE/scripts/ydeps
+if [ -f "$YSW/yconf" ]; then
+source $YSW/yconf
 else
-touch $YBASE/scripts/ydeps
+touch $YSW/yconf
 fi
 
-[ -f "$YBASE/scripts/fbuilddeps" ] && source $YBASE/scripts/fbuilddeps
+[ -f "$YDIR/scripts/fbuilddeps" ] && source $YDIR/scripts/fbuilddeps
 
-PATH=.:$YBASE/gcc/bin:/mingw32/bin:/usr/bin:/bin:`which cmd | awk '{print substr($0, 1, length($0)-4)}'`
+case "$YOS" in mingw*)
+PATH=.:$YDIR/gcc/bin:/mingw32/bin:/usr/bin:/bin:`which cmd | awk '{print substr($0, 1, length($0)-4)}'`
+esac
+
 
 [ -d "$YQT" ] && PATH=$PATH:$YQT/bin && export YQT
-[ -d "$YWX" ] && PATH=$YWX/bin:$PATH && export YWX
-
-[ -d "$YBOO" ] && export YBOO YBOOSUFFIX
+[ -d "$YWX" ] && export YWX
+[ -d "$YBOO" ] && export YBOO
 [ -d "$YOSSL" ] && export YOSSL
 [ -d "$YBDB" ] && export YBDB
 [ -d "$YLDB" ] && export YLDB
@@ -135,7 +133,6 @@ PATH=.:$YBASE/gcc/bin:/mingw32/bin:/usr/bin:/bin:`which cmd | awk '{print substr
 [ -d "$YPCRE" ] && export YPCRE
 [ -d "$YJANS" ] && export YJANS
 [ -d "$YCURL" ] && export YCURL
+[ -d "$YEVT" ] && export YEVT
 
-export PATH YDEPS YDL
-export -f yboostsuffix yinfo
-
+#[ -f "$YWX/bin/wx-config" ] && PATH=$YWX/bin:$PATH && YTMP=`wx-config --prefix` && PATH=`cygpath $YTMP`/lib:$PATH
diff --git a/yprofile b/yprofile
--- a/yprofile
+++ b/yprofile
@@ -1,4 +1,12 @@
-YBASE=/base
-[ -d "$YBASE" ] && cd $YBASE || { echo "invalid YBASE. Yenv not set. "; return 1; }
-[ -f "$YBASE/scripts/yenv" ] && source $YBASE/scripts/yenv
-export YBASE
+export YOS=`uname | awk '{print tolower($0)}'``uname -m`
+
+case $YOS in
+  linux*) YDIR=$HOME/ydir;;
+  darwin*) YDIR=$HOME/ydir;;
+  *) YDIR=/ydir;;
+esac
+
+[ -d "$YDIR" ] && cd $YDIR || { echo "invalid YDIR. Yenv not set. "; return 1; }
+[ -f "$YDIR/scripts/yenv" ] && source $YDIR/scripts/yenv
+export YDIR
+
